version: '3.7'
services:
  docker_gen:
    image: alpine/docker-gen
    volumes:
      - "/opt/docker/docker-gen-gateway/templates:/etc/docker-gen/templates:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "haconfig:/etc/haproxy/"
    command: " -notify-sighup docker-gen-haproxy_haproxy_1 -only-exposed -watch /etc/docker-gen/templates/haproxy.tmpl /etc/haproxy/haproxy.cfg"

  haproxy:
    depends_on: 
      - docker_gen
    image: alpine/haproxy
    volumes:
      - "haconfig:/etc/haproxy/:ro"
      - "crt:/crt:ro"
    networks:
      - backend-net
    ports:
      - "80:80"
      - "443:443"
    command: "-f /etc/haproxy/haproxy.cfg"

  docker_gen-cert:
    depends_on: 
      - haproxy
    image: karlyan/docker-gen-cert-bot
    volumes:
      - "/opt/docker/docker-gen-gateway/templates:/etc/docker-gen/templates:ro"
      - "/opt/docker/docker-gen-gateway/cert:/etc/letsencrypt"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "crt:/crt"
      - "nginx-srv:/srv"

networks:
  backend-net:
    name: haproxy

volumes:
  haconfig:
  nginx-srv:
  crt:
