version: '3.7'
services:
  docker_gen:
    image: alpine/docker-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./templates:/etc/docker-gen/templates:ro"
      - "./docker-gen.cfg:/etc/docker-gen/docker-gen.cfg:ro"
      - "haconfig:/etc/haproxy/"
      - "./certbot:/etc/letsencrypt"
    command: " -config /etc/docker-gen/docker-gen.cfg"

  haproxy:
    container_name: docker_gen_haproxy
    depends_on: 
      - docker_gen
    image: alpine/haproxy
    volumes:
      - "haconfig:/etc/haproxy/:ro"
      - "./haproxy-crt:/crt"
    networks:
      - backend-net
    ports:
      - "80:80"
      - "443:443"
    command: "-f /etc/haproxy/haproxy.cfg"

  nginx:
    container_name: docker_gen_letsencrypt
    depends_on:
      - docker_gen
      - haproxy
    image: alpine/enginx
    volumes:
      - "well-known:/var/www/acme:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - backend-net

  docker_gen-cert:
    depends_on: 
      - haproxy
      - nginx
      - docker_gen
    image: alpine/certbot
    volumes:
      - "./certbot:/etc/letsencrypt"
      - "./haproxy-crt:/crt"
      - "well-known:/srv"

networks:
  backend-net:
    name: haproxy

volumes:
  haconfig:
  well-known:
