version: '3.7'
services:
  nginx:
    container_name: docker_gen_letsencrypt
    image: alpine/nginx
    volumes:
      - "well-known:/var/www/acme:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - backend-net
    environment:
      - "VIRTUAL_HOST=karlyan.me"

  docker_gen:
    image: alpine/docker-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./templates:/etc/docker-gen/templates:ro"
      - "./docker-gen.cfg:/etc/docker-gen/docker-gen.cfg:ro"
      - "haconfig:/etc/haproxy/"
      - "./certbot:/etc/letsencrypt"
    command: " -config /etc/docker-gen/docker-gen.cfg"

  haproxy:
    container_name: docker_gen_haproxy
    depends_on: 
      - docker_gen
      - nginx
    image: alpine/haproxy
    volumes:
      - "haconfig:/etc/haproxy/:ro"
      - "./haproxy-crt:/crt"
    networks:
      - backend-net
    ports:
      - "80:80"
      - "443:443"
    command: "-f /etc/haproxy/haproxy.cfg"


  certbot:
    container_name: docker_gen_certbot
    depends_on: 
      - haproxy
      - nginx
      - docker_gen
    image: alpine/certbot
    volumes:
      - "./certbot:/etc/letsencrypt"
      - "./haproxy-crt:/haproxy-crt"
      - "well-known:/srv"
    environment:
      - "CERTBOT=True"

networks:
  backend-net:
    name: haproxy

volumes:
  haconfig:
  well-known:
